spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-230dcf3-germandcf-a820.a.aivencloud.com:10589/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_MYSQL_PASSWORD}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: Product-API-Auditoria

    redis:
      host: ultragentle-superb-courageous-82673.db.redis.io
      port: 16972
      username: default
      password: ${REDIS_PASSWORD}

  cache:
    type: redis

server:
  port: 8081
