spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-230dcf3-germandcf-a820.a.aivencloud.com:10589/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_MYSQL_PASSWORD}

  data:
    mongodb:
      uri: mongodb+srv://Admin:Admin@cluster0.irs5rn6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&socketTimeoutMS=30000&serverSelectionTimeoutMS=30000
      database: Product-API-Auditoria

    redis:
      host: ultragentle-superb-courageous-82673.db.redis.io
      port: 16972
      username: default
      password: OeHZasu4JswTRj9aPQ32BySY6QsE9IfV

  cache:
    type: redis

server:
  port: 8081